import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Bottombar from "@/components/Bottombar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen sm:max-w-xl mx-auto antialiased `}
      >
        <div className="h-full">{children}</div>
        <Bottombar />
      </body>
    </html>
  );
}
