import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Bottombar from "@/components/Bottombar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased flex justify-center`}>
        <div className="relative flex flex-col w-full max-w-xl min-h-screen ">
          <main className="flex-1 overflow-y-auto ">{children}</main>

          <div className="sticky bottom-0 left-0 w-full border-t border-neutral-300 bg-white">
            <Bottombar />
          </div>
        </div>
      </body>
    </html>
  );
}
